### ISSUE TITLE
"Alternative parameter name" should not be displayed if one was not set.

### ISSUE THREAD

**Issue by icnocop** [trondr/NCmdLiner#4]
Hi.

Thank you for NCmdLiner.

If I don't specify an alternative parameter name, then I don't expect "Alternative parameter name" to be displayed in the output.

For example:
```
[Command]
public static void Command1(
    [RequiredCommandParameter]
    string parameter1)
{
}
```

Expected output:
```
Commands and parameters:
------------------------
Command1
   /parameter1       [Required]
```

Actual output:
```
Commands and parameters:
------------------------
Command1
   /parameter1       [Required]   Alternative parameter name: /
```

Thank you.

**Comment by trondr** [comment]
Thanks for the feedback! This issue should be fixed in NCmdLiner.1.2.17086.228.
